### GET 보드게임리스트
GET localhost:8080/api/v1/boardgame
Content-Type:application/json
Accept:*/*


### GET 보드게임선택조회
GET localhost:8080/api/v1/boardgame/34
Content-Type:application/json
Accept:*/*

### GET 보드게임선택조회
GET localhost:8080/api/v1/boardgame/boardgameCodeWithouUrl/34
Content-Type:application/json
Accept:*/*


### PUT 보드게임수정
PUT localhost:8080/api/v1/boardgame/1
Content-Type:application/json
Accept:*/*
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMDEiLCJhdXRoIjpbIlJPTEVfVVNFUiJdLCJuaWNrbmFtZSI6IuycoOyggDAxIiwiZXhwIjoxNzE5NjEwMTUyfQ.q8uqedqS7g6am2sHCHL8QoSw09Z3ijGwsKjywjps0-aXynOnVxjDo6ZCPvd4pUTbF1BF1SJqo-x6zJNUnSK3hQ


### POST 보드게임등록
POST localhost:8080/api/v1/boardgame/1
Content-Type:application/json
Accept:*/*
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMDEiLCJhdXRoIjpbIlJPTEVfVVNFUiJdLCJuaWNrbmFtZSI6IuycoOyggDAxIiwiZXhwIjoxNzE5NjEwMTUyfQ.q8uqedqS7g6am2sHCHL8QoSw09Z3ijGwsKjywjps0-aXynOnVxjDo6ZCPvd4pUTbF1BF1SJqo-x6zJNUnSK3hQ

### DELETE 보드게임삭제
DELETE localhost:8080/api/v1/boardgame/1
Content-Type:application/json
Accept:*/*
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMDEiLCJhdXRoIjpbIlJPTEVfVVNFUiJdLCJuaWNrbmFtZSI6IuycoOyggDAxIiwiZXhwIjoxNzE5NjEwMTUyfQ.q8uqedqS7g6am2sHCHL8QoSw09Z3ijGwsKjywjps0-aXynOnVxjDo6ZCPvd4pUTbF1BF1SJqo-x6zJNUnSK3hQ

