### GET manager Store list
GET localhost:8080/api/v1/members/
Content-Type:application/json
Accept:*/*
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOlsiUk9MRV9BRE1JTiIsIlJPTEVfTUFOQUdFUiIsIlJPTEVfVVNFUiJdLCJuaWNrbmFtZSI6Iuq0gOumrOyekCIsImV4cCI6MTcxNzU3NzA1N30.ApNxXC-pCcbvY2urynfJNi3ekV1kuIIfP7o2eSZZ_cnMuBVq6hCA2Kx1XgAjf76JwoigILHZR7Ozf01v9DkUZw


### GET manager Store list
GET localhost:8080/api/v1/members/managerStore/2
Content-Type:application/json
Accept:*/*
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOlsiUk9MRV9BRE1JTiIsIlJPTEVfTUFOQUdFUiIsIlJPTEVfVVNFUiJdLCJuaWNrbmFtZSI6Iuq0gOumrOyekCIsImV4cCI6MTcxNzU3NzA1N30.ApNxXC-pCcbvY2urynfJNi3ekV1kuIIfP7o2eSZZ_cnMuBVq6hCA2Kx1XgAjf76JwoigILHZR7Ozf01v9DkUZw


### POST manager store regist
POST localhost:8080/api/v1/members/managerStore/register
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOlsiUk9MRV9BRE1JTiIsIlJPTEVfTUFOQUdFUiIsIlJPTEVfVVNFUiJdLCJuaWNrbmFtZSI6Iuq0gOumrOyekCIsImV4cCI6MTcxNzU3NzA1N30.ApNxXC-pCcbvY2urynfJNi3ekV1kuIIfP7o2eSZZ_cnMuBVq6hCA2Kx1XgAjf76JwoigILHZR7Ozf01v9DkUZw

{
  "memberCode": 21,
  "storeCode": 20
}

### PUT manager store update
PUT localhost:8080/api/v1/members/managerStore/modify
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOlsiUk9MRV9BRE1JTiIsIlJPTEVfTUFOQUdFUiIsIlJPTEVfVVNFUiJdLCJuaWNrbmFtZSI6Iuq0gOumrOyekCIsImV4cCI6MTcxNzU3NzA1N30.ApNxXC-pCcbvY2urynfJNi3ekV1kuIIfP7o2eSZZ_cnMuBVq6hCA2Kx1XgAjf76JwoigILHZR7Ozf01v9DkUZw

{
  "memberCode": 2,
  "storeCode": 1
}