xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.elasticsearch.password: ohgiraffers1234
# xpack.monitoring.elasticsearch.hosts: ["http://localhost:9200"]
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]